[colors.bright]
black = "0x4c4f69"
blue = "0x8ba1e7"
cyan = "0x9a9cfc"
green = "0xb0e57c"
magenta = "0xe0a6ff"
red = "0xff6f6f"
white = "0xffffff"
yellow = "0xffd066"

[colors.normal]
black = "0x1e1e2e"
blue = "0x6e8fdc"
cyan = "0x8d89f0"
green = "0x9bd23d"
magenta = "0xc77dff"
red = "0xef5151"
white = "0xd9e0ee"
yellow = "0xf7b14c"

# Font configuration
[font]
# Normal (roman) font face
[font.normal]
family = "0xProto Nerd Font"
style = "Regular"

# Bold font face
[font.bold]
family = "0xProto Nerd Font"
style = "Bold"

# Italic font face
[font.italic]
family = "0xProto Nerd Font"
style = "Italic"

# Bold Italic font face
[font.bold_italic]
family = "0xProto Nerd Font"
style = "Bold Italic"

# Font size
#[size]
#size = 18.0

# Padding configuration
[colors.primary]
background = "0x1e1e2e"
foreground = "0xd9e0ee"
[scrolling]
history = 10000

[shell]
args = ["--login"]
program = "/bin/bash"


